/**
 * Retention Story Intelligence — public API (Sprint 10B–10G).
 * Domain + grounding + strategy + planning + composition + budget + Hook bridge +
 * validation + rewrite terminal + production orchestration.
 * Create / Review UI should prefer `./presentation` for client-safe selectors.
 */

export {
  RETENTION_STORY_CONTRACT_VERSION,
  RETENTION_CONTRACT_FINGERPRINT_PREFIX,
  RETENTION_RESEARCH_FINGERPRINT_PREFIX,
  RETENTION_IDENTITY_FINGERPRINT_PREFIX,
  RETENTION_MIN_DURATION_SEC,
  RETENTION_MAX_DURATION_SEC,
  RETENTION_DEFAULT_DURATION_SEC,
  RETENTION_MAX_TOPIC_CHARS,
  RETENTION_MAX_MANUAL_CONTEXT_CHARS,
  RETENTION_MAX_USER_INSTRUCTIONS_CHARS,
  RETENTION_MAX_USER_AUTHORED_HOOK_CHARS,
  RETENTION_MAX_CLAIM_ID_CHARS,
  RETENTION_MAX_CLAIM_TEXT_CHARS,
  RETENTION_MAX_CLAIM_SOURCE_REF_CHARS,
  RETENTION_MAX_PI_BEAT_ID_CHARS,
  RETENTION_MAX_PI_FACT_ROLE_CHARS,
  RETENTION_MAX_GROUNDING_CLAIMS,
  RETENTION_MAX_RESEARCH_IDENTITY_CHARS,
  RETENTION_RESEARCH_IDENTITY_PATTERN,
  RETENTION_FORMAT_STRATEGY_REGISTRY_VERSION,
} from "./domain/retention-story-contract.constants";

export {
  assertRetentionResearchIdentity,
  isRetentionResearchIdentity,
} from "./domain/retention-research-identity";

export {
  RETENTION_TRUSTED_PROVIDER_SOURCES,
  isRetentionTrustedProviderSource,
  mapRetentionSourceToAuthority,
  type RetentionSourceTrustChannel,
  type RetentionSourceAuthorityMapping,
  type RetentionTrustedProviderSource,
} from "./grounding/retention-source-trust";

export type {
  StoryContractVersion,
  RetentionGenerationPath,
  StoryFormatStrategyId,
  StoryFormatStrategySelection,
  StoryDurationClass,
  AudienceIntent,
  DesiredViewerReaction,
  InformationDensity,
  VisualDensity,
  PacingProfile,
  EndingStrategy,
  RetentionClaimProvenance,
  RetentionClaimVerification,
  RetentionGroundingClaim,
  RetentionGroundingContext,
  StoryContractSemanticIdentities,
  StoryContractConstraints,
  StoryContractGroundingSummary,
  StoryContractInput,
  NormalizedStoryContract,
  RetentionFormatStrategyProfile,
  RetentionFormatCapabilityResult,
} from "./domain/retention-story-contract.types";

export {
  RetentionStoryError,
  isRetentionStoryError,
  type RetentionStoryErrorReason,
} from "./domain/retention-story-errors";

export {
  retentionStableStringify,
  retentionStableHash,
  buildRetentionSemanticIdentity,
  buildResearchIdentityFromClaims,
  buildContractFingerprint,
  type ContractFingerprintPayload,
} from "./domain/retention-story-fingerprint";

export {
  apiModeToRetentionGenerationPath,
  retentionGenerationPathToApiMode,
  isRetentionGenerationPath,
  isGenerateScriptMode,
  resolveRetentionGenerationPath,
} from "./domain/resolve-retention-generation-path";

export {
  getRetentionFormatStrategyRegistryVersion,
  listRetentionFormatStrategyProfiles,
  getRetentionFormatStrategyProfile,
  assertRetentionFormatStrategyProductionCapable,
  normalizeRetentionDurationSec,
  resolveStoryDurationClass,
  resolveAutoFormatStrategyId,
  resolveFormatStrategy,
} from "./domain/resolve-format-strategy";

export { normalizeStoryContract } from "./domain/normalize-story-contract";

export {
  buildRetentionCreatorContextAuthority,
  assertRetentionCreatorContextAuthorityMatchesContract,
  type RetentionCreatorContextAuthority,
} from "./domain/retention-creator-context-authority";

export {
  buildRetentionGroundingContext,
  graphContextHasUsableFacts,
  type BuildRetentionGroundingContextInput,
} from "./grounding/build-retention-grounding-context";

export {
  buildRetentionContentDerivedClaimId,
  finalizeRetentionGroundingClaims,
  normalizeRetentionGroundingContext,
  type RetentionGroundingClaimDraft,
} from "./grounding/retention-grounding-normalization";

export {
  RETENTION_STRATEGY_SEED_VERSION,
  RETENTION_CONTROLLING_IDEA_REGISTRY_VERSION,
  RETENTION_EMOTION_STRATEGY_REGISTRY_VERSION,
  RETENTION_MAX_CONTROLLING_IDEA_CHARS,
  RETENTION_MAX_CONTROLLING_IDEA_WORDS,
  RETENTION_MIN_CONTROLLING_IDEA_WORDS,
  RETENTION_MAX_CONTROLLING_IDEA_CANDIDATES,
  RETENTION_MAX_CONTROLLING_IDEA_CLAIM_REFS,
  extractRetentionSubjectTokens,
  statementPreservesRetentionSubject,
  claimRelevantToRetentionTopic,
  RETENTION_PARTICIPANT_COVERAGE_POLICY_VERSION,
  parseRetentionMatchupParticipantGroups,
  buildRetentionParticipantCoverage,
  toRetentionParticipantCoverageSummary,
  evaluateRetentionParticipantCoverage,
  narrationCoversRetentionParticipantGroup,
  resolveRetentionDeterministicSubjectAnchor,
  extractOrderedRetentionSubjectTokens,
  detectRetentionFactualRisk,
  getRetentionControllingIdeaRegistryVersion,
  listControllingIdeaModeStrategies,
  getControllingIdeaModeStrategy,
  assembleDeterministicControllingIdeaStatement,
  validateControllingIdea,
  isClaimEligibleForControllingIdeaSupport,
  normalizeRetentionControllingIdeaStatement,
  canonicalizeControllingIdeaClaimRefs,
  claimRefSupportsControllingIdeaStatement,
  buildControllingIdeaCandidateId,
  buildRetentionStrategySeedFingerprint,
  assertCanonicalControllingIdeaCandidate,
  assertCanonicalControllingIdeaCandidates,
  buildControllingIdeaCandidates,
  selectControllingIdea,
  getRetentionEmotionStrategyRegistryVersion,
  resolvePrimaryEmotion,
  resolveSecondaryEmotion,
  resolveEmotionalCurve,
  listRetentionEmotions,
  isRetentionEmotion,
  buildEmotionalArcBlueprint,
  validateEmotionalArcBlueprint,
  validateRetentionStrategyPlanningInput,
  buildDeterministicRetentionStrategySeed,
  normalizeRetentionStrategyProposal,
  assertRetentionStrategySeedCoherence,
  bindEmotionalArcBlueprintToBeatIds,
  type RetentionEmotion,
  type ControllingIdea,
  type ControllingIdeaSource,
  type ControllingIdeaCandidate,
  type ControllingIdeaSelection,
  type EmotionalArcPhase,
  type EmotionalIntensity,
  type EmotionalArcBlueprintPoint,
  type EmotionalArcBlueprint,
  type EmotionalArcPoint,
  type EmotionalArc,
  type RetentionStrategySeed,
  type RetentionStrategySeedResult,
  type BuildRetentionStrategySeedInput,
  type RetentionStrategyPlanningContext,
  type ControllingIdeaValidationReason,
  type ControllingIdeaValidationResult,
  type RetentionStrategyProposalInput,
  type RetentionFactualRiskResult,
  type ControllingIdeaModeStrategy,
  type ValidateControllingIdeaInput,
} from "./strategy";

export {
  RETENTION_STORY_PLAN_VERSION,
  RETENTION_BEAT_PLAN_VERSION,
  RETENTION_HOOK_HANDOFF_VERSION,
  RETENTION_BEAT_STRATEGY_REGISTRY_VERSION,
  RETENTION_BEAT_DENSITY_REGISTRY_VERSION,
  RETENTION_BEAT_ID_PREFIX,
  RETENTION_STORY_PLAN_FINGERPRINT_PREFIX,
  RETENTION_WORDS_PER_SECOND,
  RETENTION_MAX_BEAT_EMOTIONAL_INTENT_CHARS,
  RETENTION_MAX_BEAT_VIEWER_QUESTION_CHARS,
  RETENTION_MAX_BEAT_INFORMATION_CONTRIBUTION_CHARS,
  RETENTION_MAX_BEAT_NARRATION_GOAL_CHARS,
  RETENTION_MAX_BEAT_VISUAL_OPPORTUNITY_CHARS,
  RETENTION_MAX_HANDOFF_TEXT_CHARS,
  RETENTION_MAX_BEATS,
  RETENTION_MAX_PLANNER_REQUEST_CLAIMS,
  RETENTION_MAX_PLANNER_PROPOSAL_BEATS,
  RETENTION_BEAT_FORBIDDEN_LABELS,
  RETENTION_BEAT_DENSITY_PROFILES,
  RETENTION_MAX_DEAD_AIR_SEC,
  getRetentionBeatStrategyRegistryVersion,
  listRetentionBeatStrategies,
  getRetentionBeatStrategy,
  mapEndingStrategyToTerminalPurpose,
  resolveRetentionBeatPurposeSequence,
  resolveRetentionBeatControllingIdeaRelation,
  resolveRetentionBeatPayoffRelations,
  resolveRetentionBeatNoveltyRole,
  buildRetentionBeatTemplateFields,
  resolveRetentionBeatCountRange,
  resolveAdaptiveRetentionBeatCount,
  getRetentionBeatDensityProfile,
  allocateRetentionBeatBudgets,
  buildRetentionBeatId,
  buildRetentionBeatPlan,
  normalizeRetentionBeatProposal,
  buildRetentionCompressionGoals,
  buildRetentionHookHandoff,
  buildRetentionClaimIdRelationships,
  buildRetentionStoryPlanFingerprint,
  getRetentionStoryPlanRegistryVersion,
  assembleRetentionStoryPlan,
  assertRetentionStoryPlanCoherence,
  validateRetentionStoryPlan,
  reconstructPlannerBeatProposalFromPlan,
  isRetentionBeatPurpose,
  isValidRetentionPlannerPurposeSequence,
  buildDeterministicRetentionStoryPlan,
  buildRetentionStoryPlan,
  buildRetentionPlannerRequest,
  runRetentionPlannerOnce,
  sanitizeRetentionBeatText,
  canonicalRetentionBeatText,
  retentionBeatTextHasForbiddenMarker,
  type RetentionBeatDensityProfile,
  type RetentionStoryPlanVersion,
  type RetentionBeatPlanVersion,
  type RetentionHookHandoffVersion,
  type RetentionBeatPurpose,
  type RetentionBeatNoveltyRole,
  type RetentionBeatControllingIdeaRelation,
  type RetentionBeatPayoffRelation,
  type RetentionBeat,
  type RetentionBeatCountRange,
  type RetentionBeatPlan,
  type RetentionCompressionGoals,
  type RetentionHookHandoffControllingIdeaRelation,
  type RetentionHookHandoffGroundingRequirements,
  type RetentionHookHandoff,
  type RetentionStoryPlan,
  type RetentionBeatBudget,
  type RetentionBeatSemanticFields,
  type NormalizedRetentionBeatProposal,
  type NormalizedRetentionBeatProposalEntry,
  type BuildRetentionBeatPlanOptions,
  type RetentionBeatPlanResult,
  type RetentionBeatStrategy,
  type RetentionBeatCountResolution,
  type RetentionBeatIdentityPayload,
  type RetentionStoryPlanFingerprintPayload,
  type AssertRetentionStoryPlanContext,
  type RetentionPlannerClaimSummary,
  type RetentionPlannerRequest,
  type RetentionPlannerBeatProposal,
  type RetentionPlannerProposal,
  type RetentionPlannerCallback,
  type RetentionPlannerRunOutcome,
  type RetentionStoryPlanFailureReason,
  type RetentionStoryPlanOutcome,
  type RetentionStoryPlanDiagnostics,
  type RetentionStoryPlanResult,
  type BuildRetentionStoryPlanInput,
} from "./planning";

export {
  RETENTION_NARRATION_CANDIDATE_VERSION,
  RETENTION_CANDIDATE_FINGERPRINT_PREFIX,
  RETENTION_SEGMENT_SEPARATOR,
  RETENTION_MAX_SEGMENT_TEXT_CHARS,
  RETENTION_MAX_SEGMENT_CLAIM_REFS,
  RETENTION_MAX_COMPOSER_TITLE_CHARS,
  RETENTION_MAX_COMPOSER_REQUEST_CLAIMS,
  RETENTION_NARRATION_CANDIDATE_ORIGINS,
  isRetentionNarrationCandidateOrigin,
  assembleRetentionNarrationCandidate,
  buildRetentionNarrationCandidateFingerprint,
  canonicalizeRetentionSegmentText,
  normalizeRetentionComposerProposal,
  buildRetentionComposerRequest,
  buildRetentionNarrationCandidateFromProposal,
  allocateRetentionSegmentWordBudgets,
  enforceRetentionCandidateWordBudget,
  extractFirstSpokenSentence,
  validateRetentionNarrationCandidate,
  assertRetentionNarrationCandidateCoherence,
  reconcileRetentionCandidateAfterHook,
  reconcileRetentionParticipantCoverageZeroModel,
  resolvePlanAuthorizedOpeningClaimIds,
  resolvePlanAuthorizedComposerClaimIds,
  resolveAuthorizedClaimIdsForBeat,
  type RetentionNarrationCandidateOrigin,
  type RetentionNarrationCandidateVersion,
  type RetentionNarrationSegment,
  type RetentionNarrationCandidate,
  type RetentionComposerModelCallKind,
  type RetentionComposerClaimSummary,
  type RetentionComposerRequest,
  type RetentionComposerSegmentProposal,
  type RetentionComposerProposal,
  type RetentionComposerCallback,
  type BuildRetentionComposerRequestInput,
  type RetentionSegmentDraft,
  type NormalizedRetentionComposerProposal,
  type AssertRetentionNarrationCandidateContext,
  type HookApprovedOpening,
  type ReconcileRetentionCandidateAfterHookInput,
} from "./composition";

export {
  resolveRetentionModelCallBudgetPolicy,
  createRetentionModelCallLedger,
  recordDeterministicOpeningReplacement,
  emptyRetentionModelCallLedgerCounts,
  assertRetentionLedgerMatchesContract,
  assertRetentionModelCallLedgerSnapshotCoherence,
  type RetentionModelCallCategory,
  type RetentionModelCallOutcome,
  type RetentionModelCallBudgetPolicy,
  type RetentionModelCallLedgerCounts,
  type RetentionModelCallLedgerEvent,
  type RetentionModelCallLedgerSnapshot,
  type RetentionModelCallLedger,
  type AssertRetentionModelCallLedgerSnapshotOptions,
} from "./budget";

export {
  runRetentionHookBridge,
  assertRetentionHookBridgeReadyCoherence,
  type RetentionHookRunner,
  type RunRetentionHookBridgeInput,
  type RetentionHookBridgeFailureReason,
  type RetentionHookBridgeDiagnostics,
  type RetentionHookBridgeResult,
  type RetentionHookBridgeReadyResult,
  type AssertRetentionHookBridgeReadyContext,
} from "./integration";
// assertRetentionSafeHookEnvelopeCoherence — deep-import from integration/ (not a public bypass).

export {
  RETENTION_REWRITE_VERSION,
  RETENTION_REWRITE_TERMINAL_STATES,
  buildRetentionRewriteDiagnostics,
  runRetentionTerminalValidation,
  type RetentionRewriteTerminalState,
  type RetentionTerminalHookAuthority,
  type RetentionPostRewriteHookEvidence,
  type RetentionApprovedOpeningAuthority,
  type RetentionRewriteDiagnostics,
  type RetentionTerminalValidationResult,
  type RetentionBodyRewriteRequest,
  type RetentionBodyRewriteCallback,
  type RetentionTerminalScenesOnlyInput,
  type RetentionTerminalScriptPathInput,
  type RunRetentionTerminalValidationInput,
} from "./rewrite";

export {
  RETENTION_VALIDATION_VERSION,
  RETENTION_VALIDATION_FINGERPRINT_PREFIX,
  RETENTION_THRESHOLD_REGISTRY_VERSION,
  RETENTION_HEURISTIC_REGISTRY_VERSION,
  RETENTION_HARD_GATE_IDS,
  RETENTION_EDITORIAL_COMPONENT_IDS,
  RetentionValidationError,
  isRetentionValidationError,
  buildRetentionValidationFingerprint,
  buildRetentionValidationFingerprintFromResult,
  assertRetentionValidationResultCoherence,
  getRetentionThresholdRegistryVersion,
  resolveRetentionReadinessThreshold,
  usesShortRetentionWeighting,
  RETENTION_FORBIDDEN_INTRO_PATTERNS,
  matchesRetentionForbiddenIntroPattern,
  countRetentionNarrationWords,
  RETENTION_SPOKEN_COMPLETENESS_VERSION,
  evaluateRetentionSpokenCompleteness,
  validateRetentionCompressionWordPolicy,
  getRetentionHeuristicRegistryVersion,
  clamp01,
  scoreRetentionEditorialQuality,
  computeRetentionAggregates,
  buildRetentionValidationDiagnostics,
  buildSkippedScenesOnlyDiagnostics,
  validateRetentionStoryCandidate,
  type RetentionHardGateId,
  type RetentionEditorialComponentId,
  type RetentionValidationFailureClass,
  type RetentionHardGateOutcome,
  type RetentionEditorialScores,
  type RetentionValidationResult,
  type RetentionDiagnostics,
  type RetentionDiagnosticsTerminalState,
  type RetentionCompressionWordPolicyResult,
  type RetentionSpokenCompletenessReasonId,
  type RetentionSpokenCompletenessResult,
  type RetentionStoryValidationOutcome,
  type RetentionValidationErrorReason,
  type RetentionValidationFingerprintPayload,
  type ValidateRetentionStoryCandidateInput,
  type RetentionValidationCoherenceInput,
} from "./validation";

export {
  buildProductionStoryContractInput,
  mergeGroundingWithPremise,
  deriveRetentionClaimAdaptations,
  buildRetentionStoryPlanSnapshot,
  buildRetentionValidationSummary,
  commitRetentionApprovedNarration,
  buildRetentionSafeResponseEnvelope,
  buildRetentionSafeResponseEnvelopeFromApproved,
  assertNoPrivateRetentionFieldsSerialized,
  creatorSafeErrorMessage,
  mapStoryErrorReason,
  mapPlannerFailure,
  mapHookBridgeFailure,
  mapTerminalFailure,
  runRetentionProductionNarration,
  summarizeLedgerBudget,
  type RetentionStoryPlanSnapshot,
  type RetentionValidationSummary,
  type RetentionPersistedTerminalState,
  type RetentionValidationSummaryLinkage,
  validateRetentionStoryPlanSnapshot,
  validateRetentionValidationSummary,
  validateRetentionExplainabilityEnvelope,
  isCreatorStoryStrategyCoherentWithPlan,
  sanitizeCreationBriefRetentionPersistence,
  type RetentionProductionFailureCategory,
  type RetentionProductionSafeDiagnostics,
  type RetentionApprovedNarrationResult,
  type RetentionProductionNarrationResult,
  type RunRetentionProductionNarrationInput,
  type RetentionSafeResponseEnvelope,
  type CommitRetentionApprovedNarrationInput,
  type CommitRetentionApprovedNarrationResult,
  type BuildProductionStoryContractInputArgs,
  type RetentionGenerationDisposition,
  type RetentionGenerationAdaptationId,
  type RetentionGenerationDispositionSummary,
  freezeDispositionSummary,
  buildRetentionGenerationDisposition,
} from "./production";
// Commit-gate ledger + output-token helpers — deep-import from production/ (not public bypasses).
// Story Strategy UI + explainability — deep-import from presentation/ for Create/Review clients.
