/**
 * ShortForge Studio Hook Engine — public API (Sprint 7D).
 * Strategy library + validator + bounded repair + canonical integration adapter.
 */

export type {
  HookCandidate,
  HookCandidateOrigin,
  HookClaimProvenanceCategory,
  HookClaimVerificationStatus,
  HookContractVersion,
  HookDiagnostics,
  HookDirective,
  HookFallbackCallback,
  HookFallbackKind,
  HookFallbackRequest,
  HookFallbackResult,
  HookGenerationPath,
  HookGroundingClaim,
  HookGroundingContext,
  HookLengthEnforcementKind,
  HookNormalizedGroundingStatus,
  HookOpeningIntent,
  HookOpeningIntentKind,
  HookOpeningSpan,
  HookPlan,
  HookPlanSnapshot,
  HookRepairCallback,
  HookRepairRequest,
  HookRepairResult,
  HookRequestInput,
  HookResolvedConstraints,
  HookSelection,
  HookSource,
  HookStrategyId,
  HookStrategySource,
  HookValidationGroundingStatus,
  HookValidationOutcome,
  HookValidationResult,
  HookValidationScores,
  NormalizedHookRequest,
} from "./domain";

export type {
  HookSelectableStrategyId,
  HookStyleCatalogEntry,
  HookStyleReconciliationResult,
  HookStyleSelection,
  PredictedAutoHookStrategy,
  WriteMyOwnOpeningFailureReason,
  WriteMyOwnOpeningValidation,
} from "./presentation";

export {
  HOOK_INTERNAL_ONLY_STRATEGY_IDS,
  HOOK_MAX_USER_AUTHORED_HOOK_WORDS,
  HOOK_STYLE_CATALOG,
  HOOK_STYLE_INCOMPATIBLE_RESET_NOTICE,
  assertRequestedStrategyAllowed,
  countHookWords,
  formatWriteMyOwnCounter,
  getHookStyleCatalogEntry,
  hookStyleDescription,
  hookStyleLabel,
  isHookSelectableStrategyId,
  isHookStyleCompatibleWithScriptMode,
  isHookStyleSelection,
  isInternalOnlyHookStrategyId,
  listCompatibleHookStyleSelections,
  parseHookStyleSelection,
  predictAutoHookStrategy,
  reconcileHookStyleSelection,
  requestedStrategyIdFromHookStyle,
  validateWriteMyOwnOpening,
} from "./presentation";

export {
  HOOK_COMPATIBILITY_FALLBACK_STRATEGY_ID,
  HOOK_CONTRACT_VERSION,
  HOOK_DEFAULT_DURATION_SECONDS,
  HOOK_EVIDENCE_SURPRISE_STRATEGY_ID,
  HOOK_MAX_CLAIM_ID_CHARS,
  HOOK_MAX_CLAIM_TEXT_CHARS,
  HOOK_MAX_DURATION_SECONDS,
  HOOK_MAX_OPENING_STYLE_ADVISORY_CHARS,
  HOOK_MAX_USER_AUTHORED_HOOK_CHARS,
  HOOK_MIN_DURATION_SECONDS,
  HOOK_OPENING_INTENT_EVIDENCE_LED_SURPRISE,
  HOOK_PLAN_FINGERPRINT_PREFIX,
  HOOK_REQUEST_FINGERPRINT_PREFIX,
  HOOK_SPEAKING_WORDS_PER_SECOND,
  HOOK_USER_DIRECTED_STRATEGY_ID,
  HookNormalizationError,
  HookRequestPlanMismatchError,
  assertHookPlanFingerprint,
  assertHookRequestFingerprint,
  assertRequestPlanCoherence,
  buildHookPlanFingerprint,
  buildHookRequestFingerprint,
  hasEligibleVerifiedFactualClaim,
  hookStableHash,
  hookStableStringify,
  isEligibleVerifiedFactualClaim,
  normalizeGroundingClaimsForFingerprint,
  normalizeHookRequest,
  resolveNormalizedGroundingStatus,
  extractHookSubjectTokens,
  openingPreservesHookSubject,
  resolveHookExampleSubjectAnchor,
} from "./domain";

export type {
  HookStrategyDefinition,
  HookStrategyGroundingRequirement,
  HookStrategyResolution,
} from "./strategies";

export {
  buildCompatibilityFallbackPlan,
  buildHookPlan,
  buildHookPlanFromRequest,
  buildHookPlanSnapshot,
  evaluateEvidenceSurpriseEligibility,
  getCompatibilityFallbackStrategy,
  getHookStrategy,
  HOOK_SCRIPT_MODE_DEFAULT_STRATEGIES,
  HOOK_STRATEGY_IDS,
  HOOK_TEMPLATE_STRATEGY_PREFERENCES,
  isOpeningConstraintPairCoherent,
  listHookStrategies,
  resolveHookStrategy,
} from "./strategies";

export {
  assertHookCandidateId,
  buildHookCandidate,
  buildHookCandidateId,
  buildHookDiagnostics,
  buildHookSelection,
  buildHookSelectionFromValidation,
  detectFactualRiskSignals,
  extractOpeningSpan,
  HookCandidateError,
  HookDiagnosticsError,
  HookSelectionError,
  isHardGateFailure,
  isQualityOnlyFailure,
  normalizeClaimRefs,
  validateHookCandidate,
  type BuildHookCandidateInput,
  type HookFactualRiskSignals,
  type ValidateHookCandidateInput,
} from "./validation";

export {
  runBoundedHookRepair,
  assertTerminalPlanCoherence,
  HookTerminalCoherenceError,
  HOOK_USABLE_NARRATION_BODY_MIN_WORDS,
  applyDeterministicCompatibilityOpening,
  buildDeterministicCompatibilityOpening,
  hasUsableHookNarrationBody,
  replaceNarrationOpeningExact,
  type RunBoundedHookRepairInput,
  type RunBoundedHookRepairResult,
  type ReplaceNarrationOpeningResult,
} from "./repair";

export type {
  HookNeutralFactProvenance,
  HookNeutralOpeningBeatAssignment,
  HookNeutralResearchEvidence,
  HookNeutralResearchFact,
  BuildHookGenerationContextInput,
  HookAdapterTemplateContext,
  HookGenerationContext,
  GenerateHookedNarrationInput,
  GenerateHookedNarrationResult,
  HookedNarrationModelCall,
  HookedNarrationModelResult,
} from "./integration";

export {
  buildNeutralResearchEvidence,
  buildSemanticResearchFingerprint,
  buildSemanticFactId,
  buildManualFactId,
  mapNeutralEvidenceToGroundingClaims,
  buildHookDirective,
  buildBoundedPermittedClaimMap,
  buildBoundedPermittedClaimIds,
  buildHookGenerationContext,
  generateHookedNarration,
  storyScriptFromHookedNarration,
  buildCreatorFacingHookFailureMessage,
} from "./integration";

export type { DirectiveClaimEntry } from "./integration";
