/**
 * Sprint 10H — Retention Story golden fixture builders.
 * Each fixture declares request shape + what it proves for executable QA.
 */

import type { QualityMode, ScriptMode, Tone } from "@/types/footiebitz";
import type { StoryStrategySelection } from "@/features/retention-story/presentation";

import {
  RETENTION_STORY_GOLDEN_IDS,
  type RetentionStoryGoldenDescriptor,
  type RetentionStoryGoldenId,
} from "./retention-story-golden-ids";

export type RetentionGoldenGenerationPath =
  | "script_only"
  | "audio_first_full"
  | "scenes_only";

export type RetentionGoldenResearchClass =
  | "off"
  | "eligible_provider"
  | "manual_unverified"
  | "forbidden";

export type RetentionGoldenHookPath =
  | "auto"
  | "explicit_strategy"
  | "write_my_own";

export type RetentionGoldenExecutableKind =
  | "production_pass"
  | "production_scenes_only"
  | "budget_policy"
  | "grounding_reject"
  | "persistence_roundtrip"
  | "registry_only";

export interface RetentionStoryGoldenFixture {
  readonly id: RetentionStoryGoldenId;
  readonly title: string;
  readonly proves: string;
  readonly evidenceFocus: RetentionStoryGoldenDescriptor["evidenceFocus"];
  readonly executable: RetentionGoldenExecutableKind;
  readonly durationSec: number;
  readonly qualityMode: QualityMode;
  readonly storyStrategy: StoryStrategySelection;
  readonly expectedResolvedStrategy?:
    | "short_retention"
    | "short_standard"
    | "extended_short";
  readonly scriptMode: ScriptMode;
  readonly tone: Tone;
  readonly hookPath: RetentionGoldenHookPath;
  readonly hookStrategyId?: string;
  readonly userAuthoredOpening?: string;
  readonly researchClass: RetentionGoldenResearchClass;
  readonly generationPath: RetentionGoldenGenerationPath;
  readonly topic: string;
}

const DESCRIPTORS: Record<
  RetentionStoryGoldenId,
  Omit<RetentionStoryGoldenFixture, "id">
> = {
  "rs-15-auto-fast-story": {
    title: "15s Auto Fast story",
    proves: "Shortest envelope resolves Auto→Retention-first under Fast budget",
    evidenceFocus: "duration-strategy",
    executable: "production_pass",
    durationSec: 15,
    qualityMode: "cheap",
    storyStrategy: "auto",
    expectedResolvedStrategy: "short_retention",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-24-retention-balanced": {
    title: "24s Retention-first Balanced",
    proves: "Explicit Retention-first + Balanced planner evidence path",
    evidenceFocus: "duration-strategy",
    executable: "production_pass",
    durationSec: 24,
    qualityMode: "balanced",
    storyStrategy: "short_retention",
    expectedResolvedStrategy: "short_retention",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-25-auto-fast-story": {
    title: "25s Auto Fast concise band",
    proves: "Primary retention band lower edge: immediate concise narration",
    evidenceFocus: "duration-strategy",
    executable: "production_pass",
    durationSec: 25,
    qualityMode: "cheap",
    storyStrategy: "auto",
    expectedResolvedStrategy: "short_retention",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-30-auto-fast-story": {
    title: "30s Auto Fast core",
    proves: "Core Auto/Fast success: Hook+Retention approve, word budget, payoff",
    evidenceFocus: "duration-strategy",
    executable: "production_pass",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    expectedResolvedStrategy: "short_retention",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-30-retention-balanced": {
    title: "30s Retention-first Balanced",
    proves: "Core Retention-first/Balanced with planner evidence required",
    evidenceFocus: "quality-budget",
    executable: "production_pass",
    durationSec: 30,
    qualityMode: "balanced",
    storyStrategy: "short_retention",
    expectedResolvedStrategy: "short_retention",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-30-standard-balanced": {
    title: "30s Standard Balanced",
    proves: "Explicit Standard strategy under Balanced quality",
    evidenceFocus: "duration-strategy",
    executable: "production_pass",
    durationSec: 30,
    qualityMode: "balanced",
    storyStrategy: "short_standard",
    expectedResolvedStrategy: "short_standard",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-30-auto-studio": {
    title: "30s Auto Studio",
    proves: "Studio ceiling path with optional rewrite slot (≤1)",
    evidenceFocus: "quality-budget",
    executable: "production_pass",
    durationSec: 30,
    qualityMode: "best",
    storyStrategy: "auto",
    expectedResolvedStrategy: "short_retention",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-30-hook-explicit-retention": {
    title: "30s Explicit Hook + Retention-first",
    proves: "Hook Style explicit strategy independent of Story Strategy",
    evidenceFocus: "hook-path",
    executable: "production_pass",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "short_retention",
    expectedResolvedStrategy: "short_retention",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "explicit_strategy",
    hookStrategyId: "provocative_question",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-30-write-my-own-retention": {
    title: "30s Write My Own + Retention-first",
    proves: "User-authored opening path stays Retention-first coherent",
    evidenceFocus: "hook-path",
    executable: "registry_only",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "short_retention",
    expectedResolvedStrategy: "short_retention",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "write_my_own",
    userAuthoredOpening: "Spain never saw this coming",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-35-auto-fast-story": {
    title: "35s Auto Fast upper short band",
    proves: "Upper Retention-first Auto edge at 35s",
    evidenceFocus: "duration-strategy",
    executable: "production_pass",
    durationSec: 35,
    qualityMode: "cheap",
    storyStrategy: "auto",
    expectedResolvedStrategy: "short_retention",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-36-auto-fast-extended": {
    title: "36s Auto Fast extended_short",
    proves: "Auto switches to extended_short at 36s (not creator-selectable)",
    evidenceFocus: "duration-strategy",
    executable: "production_pass",
    durationSec: 36,
    qualityMode: "cheap",
    storyStrategy: "auto",
    expectedResolvedStrategy: "extended_short",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-45-auto-balanced-extended": {
    title: "45s Auto Balanced extended short",
    proves: "45s Auto/extended-short representative case",
    evidenceFocus: "duration-strategy",
    executable: "production_pass",
    durationSec: 45,
    qualityMode: "balanced",
    storyStrategy: "auto",
    expectedResolvedStrategy: "extended_short",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-60-auto-studio-extended": {
    title: "60s Auto Studio extended short",
    proves: "Longest Auto envelope under Studio budget",
    evidenceFocus: "duration-strategy",
    executable: "production_pass",
    durationSec: 60,
    qualityMode: "best",
    storyStrategy: "auto",
    expectedResolvedStrategy: "extended_short",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-mode-tactical-review": {
    title: "ScriptMode tactical_review",
    proves: "All eight ScriptModes represented — tactical_review",
    evidenceFocus: "script-mode",
    executable: "production_pass",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "tactical_review",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-mode-match-preview": {
    title: "ScriptMode match_preview",
    proves: "ScriptMode match_preview under Retention production",
    evidenceFocus: "script-mode",
    executable: "production_pass",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "match_preview",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-mode-match-recap": {
    title: "ScriptMode match_recap",
    proves: "ScriptMode match_recap under Retention production",
    evidenceFocus: "script-mode",
    executable: "production_pass",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "match_recap",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France match recap",
  },
  "rs-mode-player-analysis": {
    title: "ScriptMode player_analysis",
    proves: "ScriptMode player_analysis under Retention production",
    evidenceFocus: "script-mode",
    executable: "production_pass",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "player_analysis",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Pedri Spain midfield control analysis",
  },
  "rs-mode-top-5": {
    title: "ScriptMode top_5",
    proves: "ScriptMode top_5 under Retention production",
    evidenceFocus: "script-mode",
    executable: "production_pass",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "top_5",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Top five Spain midfield moments",
  },
  "rs-mode-historical-explainer": {
    title: "ScriptMode historical_explainer",
    proves: "ScriptMode historical_explainer under Retention production",
    evidenceFocus: "script-mode",
    executable: "production_pass",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "historical_explainer",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain France rivalry historical context",
  },
  "rs-mode-opinion-debate": {
    title: "ScriptMode opinion_debate",
    proves: "ScriptMode opinion_debate under Retention production",
    evidenceFocus: "script-mode",
    executable: "production_pass",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "opinion_debate",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical debate",
  },
  "rs-tone-funny": {
    title: "Alternate tone funny",
    proves: "Dramatic + representative alternate tones — funny",
    evidenceFocus: "tone",
    executable: "production_pass",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "story",
    tone: "funny",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-tone-tactical": {
    title: "Alternate tone tactical",
    proves: "Representative alternate tone — tactical",
    evidenceFocus: "tone",
    executable: "production_pass",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "story",
    tone: "tactical",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-research-off": {
    title: "Research off",
    proves: "Research-off path never grants factual authority",
    evidenceFocus: "research-grounding",
    executable: "production_pass",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-research-eligible-provider": {
    title: "Eligible provider evidence",
    proves: "Eligible provider claims may ground; still privacy-safe",
    evidenceFocus: "research-grounding",
    executable: "registry_only",
    durationSec: 30,
    qualityMode: "balanced",
    storyStrategy: "auto",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "eligible_provider",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-research-manual-unverified": {
    title: "Manual/unverified evidence",
    proves: "Manual/unverified never grants factual authority",
    evidenceFocus: "research-grounding",
    executable: "registry_only",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "manual_unverified",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-research-forbidden": {
    title: "Forbidden evidence",
    proves: "Forbidden evidence never grants factual authority",
    evidenceFocus: "research-grounding",
    executable: "registry_only",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "forbidden",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-path-script-only": {
    title: "Path script-only",
    proves: "script_only production path commits Retention+Hook envelopes",
    evidenceFocus: "generation-path",
    executable: "production_pass",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-path-audio-first": {
    title: "Path audio-first full",
    proves: "audio_first_full ordering: Hook+Retention before VO/scenes",
    evidenceFocus: "generation-path",
    executable: "registry_only",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "audio_first_full",
    topic: "Spain versus France tactical preview",
  },
  "rs-path-scenes-only": {
    title: "Path scenes-only",
    proves: "scenes-only: 0 model calls; narration byte-for-byte preserved",
    evidenceFocus: "generation-path",
    executable: "production_scenes_only",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "scenes_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-budget-fast-ceiling": {
    title: "Fast budget ceiling",
    proves: "Fast quality maximum 4 model calls",
    evidenceFocus: "quality-budget",
    executable: "budget_policy",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-budget-balanced-ceiling": {
    title: "Balanced budget ceiling",
    proves: "Balanced quality maximum 5 model calls + planner required",
    evidenceFocus: "quality-budget",
    executable: "budget_policy",
    durationSec: 30,
    qualityMode: "balanced",
    storyStrategy: "auto",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-budget-studio-ceiling": {
    title: "Studio budget ceiling",
    proves: "Studio quality maximum 6 model calls; rewrite ≤1",
    evidenceFocus: "quality-budget",
    executable: "budget_policy",
    durationSec: 30,
    qualityMode: "best",
    storyStrategy: "auto",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-persistence-linked-success": {
    title: "Linked persistence success",
    proves: "Successful generation persists only linked safe snapshots",
    evidenceFocus: "persistence",
    executable: "persistence_roundtrip",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "off",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
  "rs-fail-closed-unsupported-claim": {
    title: "Unsupported claim fail-closed",
    proves: "Unsupported factual claims rejected; no narration commit",
    evidenceFocus: "fail-closed",
    executable: "grounding_reject",
    durationSec: 30,
    qualityMode: "cheap",
    storyStrategy: "auto",
    scriptMode: "story",
    tone: "dramatic",
    hookPath: "auto",
    researchClass: "forbidden",
    generationPath: "script_only",
    topic: "Spain versus France tactical preview",
  },
};

export function buildRetentionStoryGoldenFixture(
  id: RetentionStoryGoldenId,
): RetentionStoryGoldenFixture {
  const base = DESCRIPTORS[id];
  if (!base) {
    throw new Error(`Unknown Retention Story golden id: ${id}`);
  }
  return { id, ...base };
}

export function listRetentionStoryGoldenFixtures(): readonly RetentionStoryGoldenFixture[] {
  return RETENTION_STORY_GOLDEN_IDS.map(buildRetentionStoryGoldenFixture);
}

export const RETENTION_STORY_GOLDEN_PROJECTS = listRetentionStoryGoldenFixtures();
