/**
 * Canonical Headless reason registry — terminal reasons must be members.
 */

import type { HeadlessReasonId } from "./headless-render.types";

export const HEADLESS_REASON_IDS = Object.freeze([
  "INVALID_REQUEST",
  "INVALID_MANIFEST",
  "MANIFEST_FINGERPRINT_MISMATCH",
  "UNSUPPORTED_MANIFEST_VERSION",
  "ASSET_COVERAGE_INCOMPLETE",
  "ASSET_COVERAGE_EXTRA",
  "ASSET_COVERAGE_DUPLICATE",
  "ASSET_COVERAGE_CONFLICT",
  "INVALID_ASSET_DESCRIPTOR",
  "INVALID_ASSET_BUNDLE",
  "INVALID_DIGEST",
  "INVALID_MIME",
  "ASSET_LIMIT_EXCEEDED",
  "INVALID_OWNERSHIP",
  "INVALID_RENDERER_PROFILE",
  "INVALID_RENDERER_BUILD",
  "INVALID_IDEMPOTENCY_KEY",
  "INVALID_JOB",
  "ILLEGAL_STATE_TRANSITION",
  "STALE_ATTEMPT",
  "TERMINAL_STATE_IMMUTABLE",
  "ARTIFACT_REQUIRED",
  "ARTIFACT_FORBIDDEN",
  "ARTIFACT_FINGERPRINT_MISMATCH",
  "ARTIFACT_REQUEST_COHERENCE_MISMATCH",
  "JOB_REQUEST_COHERENCE_MISMATCH",
  "INVALID_ARTIFACT",
  "INVALID_PROGRESS",
  "INVALID_TERMINAL_REASON",
  "INVALID_CANONICAL_ENCODING",
  "TIMESTAMP_REGRESSION",
  "UNKNOWN_FIELD",
  "HOSTILE_INPUT",
  "CANCELLED_BY_USER",
  "WORKER_FAILED",
  "QUEUE_ENQUEUE_FAILED",
  "ENCODE_FAILED",
  "ARTIFACT_PROBE_MISMATCH",
  "WORKER_TIMEOUT",
  "UNSUPPORTED_CAPABILITY",
  "WORKSPACE_QUOTA_EXCEEDED",
  "CLAIM_LEASE_EXPIRED",
  "EXPIRED",
  "ARTIFACT_CLEANUP_UNCONFIRMED",
] as const satisfies readonly HeadlessReasonId[]);

export function isHeadlessReasonId(value: unknown): value is HeadlessReasonId {
  return (
    typeof value === "string" &&
    (HEADLESS_REASON_IDS as readonly string[]).includes(value)
  );
}
